version: '3.1'

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: ddd
    ports:
      - '5432:5432'
  
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db 
    command: npm run start:dev